version: '3'

tasks:

  build:
    cmds:
      - go build .
  
  run:
    deps: [build]
    cmds:
      - ./go-esperanto
  
  test:
    cmds:
      - go test ./...
  
  vendor:
    desc: Updates the vendor directory
    cmds:
      - go mod tidy
      - go mod vendor
